(function () {
  "use strict";

  const REDUCED_MOTION = window.matchMedia("(prefers-reduced-motion: reduce)").matches;
  const TOUCH_PRIMARY_POINTER = window.matchMedia("(hover: none) and (pointer: coarse)");
  const NARROW_METHOD_VIEWPORT = window.matchMedia("(max-width: 900px)");
  const MOBILE_USER_AGENT =
    (navigator.userAgentData && navigator.userAgentData.mobile) ||
    /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent);

  const METHOD_STEPS = {
    "1": {
      label: "Step 1",
      title: "Expert Policy Training",
      copy:
        "An expert policy, policy checkpoints, and a value function are trained with established sim-to-real pipelines using privileged state.",
    },
    "2": {
      label: "Step 2",
      title: "Data Generation",
      copy:
        "Large-scale training data are generated by combining expert and sub-optimal policies with contiguous action perturbations, yielding diverse trajectories with dense reward and value supervision.",
    },
    "3": {
      label: "Step 3",
      title: "World Model Pretraining",
      copy:
        "A planning-oriented latent world model is pretrained on the generated data, learning representations, dynamics, rewards, and values from raw observations.",
    },
    "4a": {
      label: "Step 4a",
      title: "Real-World Deployment",
      copy:
        "At deployment, the learned representation and dense reward and value models are transferred to the real robot to enable sampling-based planning with the latent dynamics. This enables us to make decisions in new environments with online planning and reasoning, rather than needing to solve the difficult reinforcement learning problem.",
    },
    "4b": {
      label: "Step 4b",
      title: "Dynamics Finetuning",
      copy:
        "Real-world data is then used to finetune only the dynamics via supervised system identification, with representations, rewards, and values frozen. Deployment and finetuning are iterated, enabling rapid and stable real-world adaptation.",
    },
  };

  const METHOD_DEFAULT_STATE = {
    title: "Select a Step",
    hoverCopy: "Choose a step above or click a box in the pipeline to view its details.",
    touchCopy: "Choose a step above or tap a box in the pipeline to view its details.",
    hoverHint: "Hover over a box to view its detail below.",
    touchHint: "Tap a box to view its detail below.",
  };

  const INTERACTION_COPY = {
    methodStepHint: {
      desktop: "Click to learn more:",
      touch: "Tap to learn more:",
    },
    resultsLegend: {
      desktop: "Hover a legend item to highlight a curve.<br />Click to toggle it on/off.",
      touch: "Tap a legend item to toggle it on/off.",
    },
    resultsPlot: {
      desktop: "Hover a plot to preview its video. Click to expand.",
      touch: "Tap a plot to view its video.",
    },
    resultsChartHint: {
      desktop: "▶ Hover for video",
      touch: "▶ Tap for video",
    },
    valuesStatus: {
      desktop: "Hover over the plot to view the associated video frame.",
      touch: "Tap the plot to view the associated video frame.",
    },
    valuesLocked: {
      desktop: "Frame locked. Click or drag on the plot to change frames.",
      touch: "Frame locked. Tap or drag on the plot to change frames.",
    },
  };

  const TASK_ORDER = [
    "PEG_WIDE",
    "TABLE_WIDE",
    "PTFE",
    "PEG_NARROW",
    "TABLE_NARROW",
    "FOAM",
  ];

  const TASK_VIDEO_MAP = {
    PEG_NARROW: {
      src: "assets/video/peg_win.mp4",
      caption: "Peg insertion real-world rollouts.",
    },
    PEG_WIDE: {
      src: "assets/video/peg_win.mp4",
      caption: "Peg insertion real-world rollouts.",
    },
    TABLE_NARROW: {
      src: "assets/video/leg_win.mp4",
      caption: "Table-leg assembly real-world rollouts.",
    },
    TABLE_WIDE: {
      src: "assets/video/leg_win.mp4",
      caption: "Table-leg assembly real-world rollouts.",
    },
    PTFE: {
      src: "assets/video/ptfe_wins.mp4",
      caption: "Quadruped PTFE slope experiments.",
    },
    FOAM: {
      src: "assets/video/foam_wins.mp4",
      caption: "Quadruped foam terrain experiments.",
    },
  };

  const METHOD_COLOR_MAP = {
    "Simulation Distillation": "#4C72B0",
    "Simulation Distillation+BC": "#DD8452",
    IQL: "#55A868",
    RLPD: "#C44E52",
    SGFT: "#8172B3",
    "Diffusion Policy (Real Demos)": "#937860",
    "Diffusion Polcy (Real + Sim Demos)": "#DA8BC3",
    "pi_0.5 (Real Demos)": "#8C8C8C",
    "pi_0.5 (Real + Sim Demos)": "#CCB974",
    "Quadruped Success": "#64B5CD",
  };

  const RESULTS_METHOD_PRIORITY = [
    "Simulation Distillation",
    "Simulation Distillation+BC",
    "IQL",
    "RLPD",
    "SGFT",
    "Diffusion Policy (Real Demos)",
    "Diffusion Polcy (Real + Sim Demos)",
    "pi_0.5 (Real Demos)",
    "pi_0.5 (Real + Sim Demos)",
    "Quadruped Success",
  ];

  const resultsState = {
    data: null,
    methods: [],
    hidden: new Set(),
    hovered: null,
    selectedTask: null,
  };

  const valuesState = {
    success: [],
    fail: [],
    minStep: 0,
    maxStep: 0,
    currentStep: 0,
    locked: false,
    chart: null,
    lastWidth: 0,
    lastHeight: 0,
    resizeObserver: null,
    resizeRaf: 0,
    videoScrubState: new WeakMap(),
    objectUrls: [],
  };

  const consistencyState = {
    pretrained: [],
    finetuned: [],
    hidden: new Set(),
    hovered: null,
    lastWidth: 0,
    lastHeight: 0,
    resizeObserver: null,
    resizeRaf: 0,
  };

  function useTouchInteractionCopy() {
    return MOBILE_USER_AGENT || (TOUCH_PRIMARY_POINTER.matches && NARROW_METHOD_VIEWPORT.matches);
  }

  function addMediaQueryChangeListener(query, handler) {
    if (typeof query.addEventListener === "function") {
      query.addEventListener("change", handler);
    } else if (typeof query.addListener === "function") {
      query.addListener(handler);
    }
  }

  document.addEventListener("DOMContentLoaded", () => {
    initResponsiveInteractionCopy();
    initRevealAnimations();
    initSectionSpy();
    initHeroMotion();
    initMethodInteraction();
    initResultsDashboard();
    initValuesTimeline();
    initConsistencyLossChart();
  });

  function initRevealAnimations() {
    const nodes = document.querySelectorAll("[data-reveal]");
    if (!nodes.length) {
      return;
    }

    if (REDUCED_MOTION || !("IntersectionObserver" in window)) {
      for (const node of nodes) {
        node.classList.add("is-visible");
      }
      return;
    }

    const observer = new IntersectionObserver(
      (entries) => {
        for (const entry of entries) {
          if (entry.isIntersecting) {
            entry.target.classList.add("is-visible");
            observer.unobserve(entry.target);
          }
        }
      },
      {
        threshold: 0.2,
      }
    );

    for (const node of nodes) {
      observer.observe(node);
    }
  }

  function initResponsiveInteractionCopy() {
    const methodStepHint = document.querySelector(".method-step-hint");
    const resultsLegendHint = document.querySelector(".results-legend-hint");
    const resultsInteractionHint = document.querySelector(".results-interaction-hint");
    const valuesStatus = document.getElementById("values-status");

    const syncCopy = () => {
      const useTouchCopy = useTouchInteractionCopy();

      if (methodStepHint) {
        methodStepHint.textContent = useTouchCopy
          ? INTERACTION_COPY.methodStepHint.touch
          : INTERACTION_COPY.methodStepHint.desktop;
      }

      if (resultsLegendHint) {
        resultsLegendHint.innerHTML = useTouchCopy
          ? INTERACTION_COPY.resultsLegend.touch
          : INTERACTION_COPY.resultsLegend.desktop;
      }

      if (resultsInteractionHint) {
        resultsInteractionHint.textContent = useTouchCopy
          ? INTERACTION_COPY.resultsPlot.touch
          : INTERACTION_COPY.resultsPlot.desktop;
      }

      if (valuesStatus && !valuesState.locked) {
        valuesStatus.textContent = useTouchCopy
          ? INTERACTION_COPY.valuesStatus.touch
          : INTERACTION_COPY.valuesStatus.desktop;
      }

      const chartHints = document.querySelectorAll(".chart-video-hint");
      for (const hint of chartHints) {
        hint.textContent = useTouchCopy
          ? INTERACTION_COPY.resultsChartHint.touch
          : INTERACTION_COPY.resultsChartHint.desktop;
      }
    };

    syncCopy();
    addMediaQueryChangeListener(TOUCH_PRIMARY_POINTER, syncCopy);
    addMediaQueryChangeListener(NARROW_METHOD_VIEWPORT, syncCopy);
  }

  function initSectionSpy() {
    const navLinks = Array.from(document.querySelectorAll(".site-nav a[data-nav]"));
    if (!navLinks.length || !("IntersectionObserver" in window)) {
      return;
    }

    const idToLink = new Map();
    const sections = [];

    for (const link of navLinks) {
      const id = link.dataset.nav;
      const section = document.getElementById(id);
      if (!section) {
        continue;
      }
      sections.push(section);
      idToLink.set(id, link);
    }

    const setActive = (id) => {
      for (const link of navLinks) {
        if (link.dataset.nav === id) {
          link.setAttribute("aria-current", "true");
        } else {
          link.removeAttribute("aria-current");
        }
      }
    };

    const observer = new IntersectionObserver(
      (entries) => {
        const visible = entries
          .filter((entry) => entry.isIntersecting)
          .sort((a, b) => b.intersectionRatio - a.intersectionRatio);

        if (visible.length > 0) {
          setActive(visible[0].target.id);
        }
      },
      {
        threshold: [0.2, 0.45, 0.7],
        rootMargin: "-30% 0px -45% 0px",
      }
    );

    for (const section of sections) {
      observer.observe(section);
    }

    if (sections[0]) {
      setActive(sections[0].id);
    }
  }

  function initHeroMotion() {
    const hero = document.querySelector(".hero");
    const heroVideo = document.querySelector(".hero-video");
    if (!hero && !heroVideo) {
      return;
    }

    const onScroll = () => {
      const y = window.scrollY || 0;
      if (hero) {
        hero.classList.toggle("hero-scrolled", y > 56);
      }

      if (heroVideo && !REDUCED_MOTION) {
        const vh = Math.max(window.innerHeight, 1);
        const p = Math.min(1, y / vh);
        const scale = 1.05 + p * 0.07;
        const shift = p * 26;
        heroVideo.style.transform =
          "translate3d(0," + shift.toFixed(2) + "px,0) scale(" + scale.toFixed(4) + ")";
      }
    };

    onScroll();
    window.addEventListener("scroll", onScroll, { passive: true });
  }

  function initMethodInteraction() {
    const interactionHint = document.querySelector(".method-interaction-hint");
    const nodes = Array.from(document.querySelectorAll(".method-node"));
    const title = document.getElementById("method-step-title");
    const copy = document.getElementById("method-step-copy");
    const stepButtons = Array.from(document.querySelectorAll(".method-step-button"));
    const methodSection = document.getElementById("method");
    const methodShell = document.querySelector(".method-shell");
    const figure = document.querySelector(".method-figure");
    const siteHeader = document.querySelector(".site-header");
    const panel = document.querySelector(".method-panel");
    const scrollShell = document.querySelector(".method-scroll-shell");
    const scrollFrame = document.querySelector(".method-scroll-frame");

    if (!nodes.length || !title || !copy || !panel || !methodSection || !methodShell || !figure) {
      return;
    }

    const getMethodDefaultCopy = () => {
      return useTouchInteractionCopy()
        ? {
            hint: METHOD_DEFAULT_STATE.touchHint,
            copy: METHOD_DEFAULT_STATE.touchCopy,
          }
        : {
            hint: METHOD_DEFAULT_STATE.hoverHint,
            copy: METHOD_DEFAULT_STATE.hoverCopy,
          };
    };

    const shouldUseMethodTouchPan = () => {
      if (!scrollFrame) {
        return false;
      }

      return useTouchInteractionCopy() && scrollFrame.scrollWidth > scrollFrame.clientWidth + 12;
    };

    const applyStep = (stepId) => {
      const payload = METHOD_STEPS[stepId];
      if (!payload) {
        return;
      }

      title.textContent = payload.title;
      copy.textContent = payload.copy;

      for (const node of nodes) {
        node.classList.toggle("active", node.dataset.step === stepId);
      }

      for (const button of stepButtons) {
        const isActive = button.dataset.step === stepId;
        button.classList.toggle("active", isActive);
        button.setAttribute("aria-pressed", isActive ? "true" : "false");
      }
    };

    const clearStepSelection = () => {
      const defaultCopy = getMethodDefaultCopy();
      if (interactionHint) {
        interactionHint.textContent = defaultCopy.hint;
      }
      title.textContent = METHOD_DEFAULT_STATE.title;
      copy.textContent = defaultCopy.copy;

      for (const node of nodes) {
        node.classList.remove("active", "method-node-guided");
      }

      for (const button of stepButtons) {
        button.classList.remove("active");
        button.setAttribute("aria-pressed", "false");
      }
    };

    const syncMethodInteractionCopy = () => {
      const defaultCopy = getMethodDefaultCopy();
      if (interactionHint) {
        interactionHint.textContent = defaultCopy.hint;
      }

      if (scrollFrame) {
        scrollFrame.style.touchAction = shouldUseMethodTouchPan() ? "pan-y pinch-zoom" : "";
      }

      const hasActiveStep = stepButtons.some((button) => button.classList.contains("active"));
      if (!hasActiveStep) {
        title.textContent = METHOD_DEFAULT_STATE.title;
        copy.textContent = defaultCopy.copy;
      }
    };

    let guidedNodeTimer = 0;
    const focusMethodNodeFromSheet = (stepId) => {
      if (!scrollFrame || !methodSection.classList.contains("method-sheet-enabled")) {
        return;
      }

      const targetNode = nodes.find((node) => node.dataset.step === stepId);
      if (!targetNode) {
        return;
      }

      const frameWidth = scrollFrame.clientWidth;
      if (frameWidth > 0) {
        const maxScroll = Math.max(0, scrollFrame.scrollWidth - frameWidth);
        const leftInset = 20;
        const targetScrollLeft = Math.max(
          0,
          Math.min(maxScroll, targetNode.offsetLeft - leftInset)
        );

        scrollFrame.scrollTo({
          left: targetScrollLeft,
          behavior: REDUCED_MOTION ? "auto" : "smooth",
        });
      }

      const nodeRect = targetNode.getBoundingClientRect();
      const nodeCenterAbsoluteY = window.scrollY + nodeRect.top + nodeRect.height / 2;
      const headerBottom = siteHeader ? siteHeader.getBoundingClientRect().bottom : 0;
      const panelTop = methodSection.classList.contains("method-sheet-active")
        ? panel.getBoundingClientRect().top
        : window.innerHeight;
      const visibleTop = headerBottom + 12;
      const visibleBottom = Math.max(visibleTop + 40, panelTop - 12);
      const targetCenterViewportY = (visibleTop + visibleBottom) / 2;
      const targetScrollTop = Math.max(0, nodeCenterAbsoluteY - targetCenterViewportY);

      window.scrollTo({
        top: targetScrollTop,
        behavior: REDUCED_MOTION ? "auto" : "smooth",
      });

      if (guidedNodeTimer) {
        window.clearTimeout(guidedNodeTimer);
      }

      for (const node of nodes) {
        node.classList.remove("method-node-guided");
      }

      if (REDUCED_MOTION) {
        return;
      }

      void targetNode.offsetWidth;
      targetNode.classList.add("method-node-guided");
      guidedNodeTimer = window.setTimeout(() => {
        targetNode.classList.remove("method-node-guided");
        guidedNodeTimer = 0;
      }, 950);
    };

    const measurePanelHeightForWidth = (panelWidth) => {
      if (panelWidth <= 0) {
        return 0;
      }

      const probe = panel.cloneNode(true);
      const probeTitle = probe.querySelector("#method-step-title");
      const probeCopy = probe.querySelector("#method-step-copy");

      if (!probeTitle || !probeCopy) {
        return 0;
      }

      probe.removeAttribute("data-reveal");
      probe.style.position = "absolute";
      probe.style.left = "-9999px";
      probe.style.top = "0";
      probe.style.visibility = "hidden";
      probe.style.pointerEvents = "none";
      probe.style.height = "auto";
      probe.style.minHeight = "0";
      probe.style.width = panelWidth + "px";

      document.body.appendChild(probe);

      let maxHeight = 0;
      for (const payload of Object.values(METHOD_STEPS)) {
        probeTitle.textContent = payload.title;
        probeCopy.textContent = payload.copy;
        maxHeight = Math.max(maxHeight, Math.ceil(probe.getBoundingClientRect().height));
      }

      probe.remove();

      return maxHeight;
    };

    const applyPanelSizeForLongestStep = () => {
      const panelWidth = panel.getBoundingClientRect().width;
      const maxHeight = measurePanelHeightForWidth(panelWidth);
      if (maxHeight > 0) {
        panel.style.minHeight = maxHeight + "px";
      }
    };

    const shouldUseFloatingSheet = () => {
      const shellWidth = methodShell.getBoundingClientRect().width;
      const figureHeight = Math.ceil(figure.getBoundingClientRect().height);
      if (shellWidth <= 0 || figureHeight <= 0) {
        return false;
      }

      const shellStyles = window.getComputedStyle(methodShell);
      const gap = Number.parseFloat(shellStyles.rowGap || shellStyles.gap || "0") || 0;
      const naturalPanelHeight = measurePanelHeightForWidth(shellWidth);

      if (naturalPanelHeight <= 0) {
        return false;
      }

      return figureHeight + naturalPanelHeight + gap + 32 > window.innerHeight;
    };

    const updateFloatingSheetVisibility = () => {
      const sheetEnabled = methodSection.classList.contains("method-sheet-enabled");
      if (!sheetEnabled) {
        methodSection.classList.remove("method-sheet-active");
        return;
      }

      const rect = methodSection.getBoundingClientRect();
      const panelHeight = Math.ceil(panel.getBoundingClientRect().height);
      const enterThreshold = Math.ceil(panelHeight * 1.25);
      const exitThreshold = Math.ceil(panelHeight * 1.00);
      // const exitThreshold = Math.max(140, Math.min(220, Math.ceil(panelHeight * 0.62)));
      const isActive = rect.top < window.innerHeight - enterThreshold && rect.bottom > exitThreshold;
      methodSection.classList.toggle("method-sheet-active", isActive);
    };

    const updateFloatingSheetMode = () => {
      const shouldFloat = shouldUseFloatingSheet();
      methodSection.classList.toggle("method-sheet-enabled", shouldFloat);

      if (!shouldFloat) {
        methodSection.classList.remove("method-sheet-active");
        return;
      }

      updateFloatingSheetVisibility();
    };

    const updateScrollIndicators = () => {
      if (!scrollShell || !scrollFrame) {
        return;
      }

      const maxScroll = Math.max(0, scrollFrame.scrollWidth - scrollFrame.clientWidth);
      const reachedRightEdge = maxScroll > 12 && scrollFrame.scrollLeft >= maxScroll - 12;
      const canScrollLeft = reachedRightEdge;
      const canScrollRight = maxScroll > 12 && scrollFrame.scrollLeft < maxScroll - 12;

      scrollShell.classList.toggle("can-scroll-left", canScrollLeft);
      scrollShell.classList.toggle("can-scroll-right", canScrollRight);
    };

    let resizeFrame = 0;
    const queueLayoutUpdate = () => {
      if (resizeFrame) {
        window.cancelAnimationFrame(resizeFrame);
      }
      resizeFrame = window.requestAnimationFrame(() => {
        resizeFrame = 0;
        updateFloatingSheetMode();
        applyPanelSizeForLongestStep();
        updateFloatingSheetMode();
        syncMethodInteractionCopy();
        updateScrollIndicators();
      });
    };

    let visibilityFrame = 0;
    const queueFloatingSheetVisibility = () => {
      if (visibilityFrame) {
        window.cancelAnimationFrame(visibilityFrame);
      }
      visibilityFrame = window.requestAnimationFrame(() => {
        visibilityFrame = 0;
        updateFloatingSheetVisibility();
      });
    };

    for (const node of nodes) {
      const step = node.dataset.step;
      const handler = () => applyStep(step);
      node.addEventListener("mouseenter", handler);
      node.addEventListener("focus", handler);
      node.addEventListener("click", handler);
    }

    for (const button of stepButtons) {
      button.setAttribute("aria-pressed", "false");
      button.addEventListener("click", () => {
        applyStep(button.dataset.step);
        focusMethodNodeFromSheet(button.dataset.step);
      });
    }

    if (scrollFrame) {
      scrollFrame.addEventListener("scroll", updateScrollIndicators, { passive: true });

      let touchPanState = null;
      let queuedTouchPanFrame = 0;
      let queuedTouchPanLeft = scrollFrame.scrollLeft;

      const flushTouchPan = () => {
        queuedTouchPanFrame = 0;
        scrollFrame.scrollLeft = queuedTouchPanLeft;
      };

      const queueTouchPan = (nextLeft) => {
        queuedTouchPanLeft = nextLeft;

        if (queuedTouchPanFrame) {
          return;
        }

        queuedTouchPanFrame = window.requestAnimationFrame(flushTouchPan);
      };

      scrollFrame.addEventListener(
        "touchstart",
        (event) => {
          if (!shouldUseMethodTouchPan() || event.touches.length !== 1) {
            touchPanState = null;
            return;
          }

          if (queuedTouchPanFrame) {
            window.cancelAnimationFrame(queuedTouchPanFrame);
            flushTouchPan();
          }

          const touch = event.touches[0];
          touchPanState = {
            startX: touch.clientX,
            startY: touch.clientY,
            startScrollLeft: scrollFrame.scrollLeft,
            dragging: false,
            horizontalDragActive: false,
          };
          queuedTouchPanLeft = touchPanState.startScrollLeft;
        },
        { passive: true }
      );

      scrollFrame.addEventListener(
        "touchmove",
        (event) => {
          if (!shouldUseMethodTouchPan() || !touchPanState || event.touches.length !== 1) {
            return;
          }

          const touch = event.touches[0];
          const deltaX = touchPanState.startX - touch.clientX;
          const deltaY = touchPanState.startY - touch.clientY;
          const absDeltaX = Math.abs(deltaX);
          const absDeltaY = Math.abs(deltaY);

          if (!touchPanState.dragging && absDeltaX + absDeltaY < 6) {
            return;
          }

          touchPanState.dragging = true;
          if (!touchPanState.horizontalDragActive) {
            // Let pure vertical swipes stay native. Only steer the pipeline once
            // there is clear horizontal intent, including diagonal drags.
            if (absDeltaX < 10 || absDeltaX < absDeltaY * 0.5) {
              return;
            }

            touchPanState.horizontalDragActive = true;
          }

          queueTouchPan(touchPanState.startScrollLeft + deltaX);
        },
        { passive: true }
      );

      const resetTouchPanState = () => {
        if (queuedTouchPanFrame) {
          window.cancelAnimationFrame(queuedTouchPanFrame);
          flushTouchPan();
        }
        touchPanState = null;
      };

      scrollFrame.addEventListener("touchend", resetTouchPanState, { passive: true });
      scrollFrame.addEventListener("touchcancel", resetTouchPanState, { passive: true });

      if ("ResizeObserver" in window) {
        const scrollResizeObserver = new ResizeObserver(queueLayoutUpdate);
        scrollResizeObserver.observe(scrollFrame);
      }
    }

    clearStepSelection();
    syncMethodInteractionCopy();
    updateFloatingSheetMode();
    applyPanelSizeForLongestStep();
    updateFloatingSheetMode();
    updateScrollIndicators();
    window.addEventListener("resize", queueLayoutUpdate, { passive: true });
    window.addEventListener("load", queueLayoutUpdate, { passive: true });
    window.addEventListener("scroll", queueFloatingSheetVisibility, { passive: true });
    if (document.fonts && document.fonts.ready) {
      document.fonts.ready.then(queueLayoutUpdate);
    }
    addMediaQueryChangeListener(TOUCH_PRIMARY_POINTER, syncMethodInteractionCopy);
    addMediaQueryChangeListener(NARROW_METHOD_VIEWPORT, syncMethodInteractionCopy);
  }

  async function initResultsDashboard() {
    const grid = document.getElementById("results-grid");
    const legendRoot = document.getElementById("results-legend");
    const panel = document.querySelector(".results-panel");

    if (!grid || !legendRoot || !panel) {
      return;
    }

    let payload = null;
    try {
      const response = await fetch("assets/data/results.json", { cache: "no-store" });
      if (!response.ok) {
        throw new Error("Failed to load results.json");
      }
      payload = await response.json();
    } catch (error) {
      const notice = document.createElement("p");
      notice.textContent = "Interactive charts could not be loaded. Static fallback remains visible.";
      grid.prepend(notice);
      return;
    }

    resultsState.data = payload;
    resultsState.selectedTask = TASK_ORDER.find((key) => payload[key]) || null;
    resultsState.methods = collectMethodNames(payload);

    buildLegend(legendRoot, resultsState.methods);
    initResultsVideoModal();

    renderResultsCharts();
    refreshLegendUI();
    hideResultsHoverPreview();

    panel.addEventListener("mouseleave", () => {
      hideResultsHoverPreview();
    });
  }

  function collectMethodNames(data) {
    const names = new Set();

    for (const key of TASK_ORDER) {
      const task = data[key];
      if (!task) {
        continue;
      }
      for (const name of Object.keys(task.data || {})) {
        names.add(name);
      }
      for (const name of Object.keys(task.lines || {})) {
        names.add(name);
      }
    }

    const ordered = [];
    for (const item of RESULTS_METHOD_PRIORITY) {
      if (names.has(item)) {
        ordered.push(item);
        names.delete(item);
      }
    }

    for (const item of names) {
      ordered.push(item);
    }

    return ordered;
  }

  function buildLegend(root, methods) {
    root.innerHTML = "";

    for (const method of methods) {
      const button = document.createElement("button");
      button.type = "button";
      button.className = "legend-item";
      button.dataset.method = method;

      const swatch = document.createElement("span");
      swatch.className = "legend-swatch";
      swatch.style.backgroundColor = colorForMethod(method);

      const label = document.createElement("span");
      renderMethodLabel(label, method);

      button.appendChild(swatch);
      button.appendChild(label);

      button.addEventListener("mouseenter", () => {
        resultsState.hovered = method;
        refreshLegendUI();
        renderResultsCharts();
      });

      button.addEventListener("mouseleave", () => {
        if (resultsState.hovered === method) {
          resultsState.hovered = null;
          refreshLegendUI();
          renderResultsCharts();
        }
      });

      button.addEventListener("focus", () => {
        resultsState.hovered = method;
        refreshLegendUI();
        renderResultsCharts();
      });

      button.addEventListener("blur", () => {
        if (resultsState.hovered === method) {
          resultsState.hovered = null;
          refreshLegendUI();
          renderResultsCharts();
        }
      });

      button.addEventListener("click", () => {
        if (resultsState.hidden.has(method)) {
          resultsState.hidden.delete(method);
        } else {
          resultsState.hidden.add(method);
        }
        refreshLegendUI();
        renderResultsCharts();
      });

      root.appendChild(button);
    }

    const resetButton = document.createElement("button");
    resetButton.type = "button";
    resetButton.id = "legend-reset";
    resetButton.className = "legend-item legend-item-reset";
    resetButton.textContent = "Reset";
    resetButton.addEventListener("click", () => {
      resultsState.hidden.clear();
      resultsState.hovered = null;
      refreshLegendUI();
      renderResultsCharts();
    });
    root.appendChild(resetButton);
  }

  function renderMethodLabel(node, methodName) {
    const match = methodName.match(/^pi_([0-9.]+)(.*)$/);
    if (!match) {
      node.textContent = methodName;
      return;
    }

    const [, subscript, suffix] = match;
    node.textContent = "";
    node.appendChild(document.createTextNode("π"));
    const sub = document.createElement("sub");
    sub.textContent = subscript;
    node.appendChild(sub);
    if (suffix) {
      node.appendChild(document.createTextNode(suffix));
    }
  }

  function refreshLegendUI() {
    const legendButtons = document.querySelectorAll(".legend-item[data-method]");

    for (const button of legendButtons) {
      const method = button.dataset.method;
      button.classList.toggle("hidden", resultsState.hidden.has(method));
      button.classList.toggle("hovered", resultsState.hovered === method);
      button.setAttribute("aria-pressed", resultsState.hidden.has(method) ? "true" : "false");
    }

    const resetButton = document.getElementById("legend-reset");
    if (resetButton) {
      const shouldShow = resultsState.hidden.size > 0;
      resetButton.classList.toggle("is-visible", shouldShow);
      resetButton.setAttribute("aria-hidden", shouldShow ? "false" : "true");
      resetButton.tabIndex = shouldShow ? 0 : -1;
    }
  }

  function renderResultsCharts() {
    const grid = document.getElementById("results-grid");
    if (!grid || !resultsState.data) {
      return;
    }

    hideResultsHoverPreview();
    grid.innerHTML = "";

    for (const key of TASK_ORDER) {
      const task = resultsState.data[key];
      if (!task) {
        continue;
      }

      const card = document.createElement("article");
      card.className = "chart-card";
      card.dataset.task = key;
      card.tabIndex = 0;

      const title = document.createElement("h3");
      title.textContent = task.title;

      const hoverHint = document.createElement("span");
      hoverHint.className = "chart-video-hint";
      hoverHint.textContent = useTouchInteractionCopy()
        ? INTERACTION_COPY.resultsChartHint.touch
        : INTERACTION_COPY.resultsChartHint.desktop;

      const wrap = document.createElement("div");
      wrap.className = "chart-wrap";
      wrap.appendChild(buildTaskChartSvg(task));

      card.appendChild(hoverHint);
      card.appendChild(title);
      card.appendChild(wrap);

      const selectTask = () => {
        resultsState.selectedTask = key;
        markSelectedTaskCard();
      };

      const previewOnPointer = (event) => {
        selectTask();
        showResultsHoverPreview(key, event, card);
      };

      card.addEventListener("mouseenter", previewOnPointer);
      card.addEventListener("mousemove", previewOnPointer);
      card.addEventListener("focus", () => {
        selectTask();
        showResultsHoverPreview(key, null, card);
      });
      card.addEventListener("blur", () => {
        hideResultsHoverPreview();
      });
      card.addEventListener("mouseleave", () => {
        hideResultsHoverPreview();
      });
      card.addEventListener("click", (event) => {
        selectTask();
        showResultsHoverPreview(key, event, card);
        openResultsVideoModal(key);
      });

      grid.appendChild(card);
    }

    markSelectedTaskCard();
  }

  function markSelectedTaskCard() {
    const cards = document.querySelectorAll(".chart-card");
    for (const card of cards) {
      const isSelected = card.dataset.task === resultsState.selectedTask;
      card.classList.toggle("is-selected", isSelected);
    }
  }

  function showResultsHoverPreview(taskKey, event, anchorCard) {
    const panel = document.querySelector(".results-panel");
    const preview = document.getElementById("results-hover-preview");
    const title = document.getElementById("results-hover-preview-title");
    const video = document.getElementById("results-hover-preview-video");

    if (!panel || !preview || !title || !video || !resultsState.data) {
      return;
    }

    const task = resultsState.data[taskKey];
    if (!task) {
      return;
    }

    const mapping = TASK_VIDEO_MAP[taskKey] || TASK_VIDEO_MAP.PEG_NARROW;
    title.textContent = task.title;

    if (video.getAttribute("src") !== mapping.src) {
      video.setAttribute("src", mapping.src);
      video.load();
    }

    preview.classList.add("is-visible");
    preview.setAttribute("aria-hidden", "false");
    positionResultsHoverPreview(preview, panel, event, anchorCard);
    if (video.paused) {
      safePlay(video);
    }
  }

  function hideResultsHoverPreview() {
    const preview = document.getElementById("results-hover-preview");
    const video = document.getElementById("results-hover-preview-video");
    if (preview) {
      preview.classList.remove("is-visible");
      preview.setAttribute("aria-hidden", "true");
    }
    if (video) {
      video.pause();
    }
  }

  function initResultsVideoModal() {
    const modal = document.getElementById("results-video-modal");
    const closeButton = document.getElementById("results-modal-close");
    if (!modal || !closeButton || modal.dataset.bound === "true") {
      return;
    }

    modal.dataset.bound = "true";

    closeButton.addEventListener("click", () => {
      closeResultsVideoModal();
    });

    modal.addEventListener("click", (event) => {
      if (event.target === modal) {
        closeResultsVideoModal();
      }
    });

    document.addEventListener("keydown", (event) => {
      if (event.key === "Escape" && modal.classList.contains("is-open")) {
        closeResultsVideoModal();
      }
    });
  }

  function openResultsVideoModal(taskKey) {
    const modal = document.getElementById("results-video-modal");
    const title = document.getElementById("results-modal-title");
    const video = document.getElementById("results-modal-video");
    if (!modal || !title || !video || !resultsState.data) {
      return;
    }

    const task = resultsState.data[taskKey];
    if (!task) {
      return;
    }

    const mapping = TASK_VIDEO_MAP[taskKey] || TASK_VIDEO_MAP.PEG_NARROW;
    title.textContent = task.title;
    if (video.getAttribute("src") !== mapping.src) {
      video.setAttribute("src", mapping.src);
      video.load();
    }

    hideResultsHoverPreview();
    modal.hidden = false;
    modal.classList.add("is-open");
    document.body.classList.add("results-modal-open");
    safePlay(video);
  }

  function closeResultsVideoModal() {
    const modal = document.getElementById("results-video-modal");
    const video = document.getElementById("results-modal-video");
    if (!modal || !video) {
      return;
    }

    modal.classList.remove("is-open");
    modal.hidden = true;
    document.body.classList.remove("results-modal-open");
    video.pause();
  }

  function positionResultsHoverPreview(preview, panel, event, anchorCard) {
    const panelRect = panel.getBoundingClientRect();
    const padding = 10;
    let x = padding;
    let y = padding;

    if (event && Number.isFinite(event.clientX) && Number.isFinite(event.clientY)) {
      x = event.clientX - panelRect.left + 16;
      y = event.clientY - panelRect.top + 16;
    } else if (anchorCard) {
      const cardRect = anchorCard.getBoundingClientRect();
      x = cardRect.right - panelRect.left + 14;
      y = cardRect.top - panelRect.top + 10;
    }

    const previewWidth = preview.offsetWidth || 320;
    const previewHeight = preview.offsetHeight || 250;

    if (x + previewWidth > panelRect.width - padding) {
      x -= previewWidth + 32;
    }
    if (y + previewHeight > panelRect.height - padding) {
      y = panelRect.height - previewHeight - padding;
    }

    x = Math.max(padding, x);
    y = Math.max(padding, y);

    preview.style.left = x.toFixed(1) + "px";
    preview.style.top = y.toFixed(1) + "px";
  }

  function buildTaskChartSvg(task) {
    const width = 560;
    const height = 340;
    const margin = { top: 16, right: 14, bottom: 58, left: 70 };
    const plotWidth = width - margin.left - margin.right;
    const plotHeight = height - margin.top - margin.bottom;

    const allDataSeries = Object.entries(task.data || {});
    const allLineSeries = Object.entries(task.lines || {});

    const visibleDataSeries = allDataSeries.filter(([name]) => !resultsState.hidden.has(name));
    const visibleLineSeries = allLineSeries.filter(([name]) => !resultsState.hidden.has(name));

    const xValues = (task.x || []).slice();
    const xMin = Math.min.apply(null, xValues);
    const xMax = Math.max.apply(null, xValues);

    const yValues = [];
    for (const [, values] of visibleDataSeries) {
      for (const value of values) {
        yValues.push(value);
      }
    }
    for (const [, value] of visibleLineSeries) {
      yValues.push(value);
    }

    if (!yValues.length) {
      yValues.push(0, 1);
    }

    let yMin = Math.min.apply(null, yValues);
    let yMax = Math.max.apply(null, yValues);

    if (yMax <= 1.1) {
      yMin = 0;
      yMax = Math.max(1, yMax * 1.08);
    } else {
      yMin = Math.min(0, yMin * 0.95);
      yMax = yMax * 1.05;
    }

    const customYMaxRaw = task.y_max ?? task.yMax ?? task.ymax;
    const customYMax = Number(customYMaxRaw);
    if (Number.isFinite(customYMax)) {
      yMax = customYMax;
      if (yMax <= yMin) {
        yMin = Math.min(0, yMax - 1);
      }
    }

    if (Math.abs(yMax - yMin) < 1e-8) {
      yMax = yMin + 1;
    }

    const scaleX = (x) => margin.left + ((x - xMin) / (xMax - xMin || 1)) * plotWidth;
    const scaleY = (y) => margin.top + (1 - (y - yMin) / (yMax - yMin || 1)) * plotHeight;

    const svg = createSvgElement("svg", {
      class: "chart-svg",
      viewBox: "0 0 " + width + " " + height,
      role: "img",
      "aria-label": task.title,
    });

    const plotRect = createSvgElement("rect", {
      x: margin.left,
      y: margin.top,
      width: plotWidth,
      height: plotHeight,
      fill: "#ffffff",
      stroke: "rgba(16, 23, 34, 0.12)",
      "stroke-width": "1",
      rx: "8",
    });
    svg.appendChild(plotRect);

    const yTicks = 5;
    for (let i = 0; i < yTicks; i += 1) {
      const t = i / (yTicks - 1);
      const value = yMin + (1 - t) * (yMax - yMin);
      const y = margin.top + t * plotHeight;

      svg.appendChild(
        createSvgElement("line", {
          x1: margin.left,
          y1: y,
          x2: margin.left + plotWidth,
          y2: y,
          stroke: "rgba(16, 23, 34, 0.13)",
          "stroke-width": i === yTicks - 1 ? "1.1" : "0.8",
        })
      );

      svg.appendChild(
        createSvgElement("text", {
          x: margin.left - 8,
          y: y + 4,
          fill: "#49576a",
          "font-size": "14",
          "text-anchor": "end",
          "font-family": "Sora, sans-serif",
          textContent: formatTick(value),
        })
      );
    }

    const xTickValues = pickXAxisTicks(xValues);
    for (const value of xTickValues) {
      const x = scaleX(value);
      svg.appendChild(
        createSvgElement("line", {
          x1: x,
          y1: margin.top,
          x2: x,
          y2: margin.top + plotHeight,
          stroke: "rgba(16, 23, 34, 0.08)",
          "stroke-width": "0.8",
        })
      );

      svg.appendChild(
        createSvgElement("text", {
          x: x,
          y: margin.top + plotHeight + 22,
          fill: "#49576a",
          "font-size": "14",
          "text-anchor": "middle",
          "font-family": "Sora, sans-serif",
          textContent: String(value),
        })
      );
    }

    for (const [name, yValue] of visibleLineSeries) {
      const y = scaleY(yValue);
      const isHovered = resultsState.hovered === name;
      const isMuted = Boolean(resultsState.hovered && !isHovered);
      const opacity = isMuted ? 0.22 : 0.78;

      svg.appendChild(
        createSvgElement("line", {
          x1: margin.left,
          y1: y,
          x2: margin.left + plotWidth,
          y2: y,
          stroke: colorForMethod(name),
          "stroke-width": isHovered ? "4" : "3",
          "stroke-dasharray": "6 5",
          "stroke-linecap": "round",
          opacity: String(opacity),
        })
      );
    }

    for (const [name, values] of visibleDataSeries) {
      const points = [];
      const len = Math.min(values.length, xValues.length);
      for (let i = 0; i < len; i += 1) {
        points.push([scaleX(xValues[i]), scaleY(values[i])]);
      }

      if (!points.length) {
        continue;
      }

      const isHovered = resultsState.hovered === name;
      const isMuted = Boolean(resultsState.hovered && !isHovered);
      const lineOpacity = isMuted ? 0.22 : 1;
      const strokeWidth = isHovered ? 4.2 : 3.2;

      const d = points
        .map((point, index) => (index === 0 ? "M" : "L") + point[0].toFixed(2) + " " + point[1].toFixed(2))
        .join(" ");

      svg.appendChild(
        createSvgElement("path", {
          d,
          fill: "none",
          stroke: colorForMethod(name),
          "stroke-width": String(strokeWidth),
          "stroke-linejoin": "round",
          "stroke-linecap": "round",
          opacity: String(lineOpacity),
        })
      );

      for (const point of points) {
        svg.appendChild(
          createSvgElement("circle", {
            cx: point[0],
            cy: point[1],
            r: isHovered ? "5.8" : "4.8",
            fill: colorForMethod(name),
            stroke: "none",
            "stroke-width": "0",
            opacity: String(lineOpacity),
          })
        );
      }
    }

    svg.appendChild(
      createSvgElement("text", {
        x: margin.left + plotWidth / 2,
        y: height - 10,
        fill: "#3a4657",
        "font-size": "16",
        "text-anchor": "middle",
        "font-family": "Sora, sans-serif",
        textContent: task.xlabel,
      })
    );

    svg.appendChild(
      createSvgElement("text", {
        x: 16,
        y: margin.top + plotHeight / 2,
        fill: "#3a4657",
        "font-size": "16",
        "text-anchor": "middle",
        transform: "rotate(-90 16 " + (margin.top + plotHeight / 2) + ")",
        "font-family": "Sora, sans-serif",
        textContent: task.ylabel,
      })
    );

    return svg;
  }

  async function initValuesTimeline() {
    const svg = document.getElementById("values-chart");
    if (!svg) {
      return;
    }

    try {
      const [successText, failText] = await Promise.all([
        fetch("assets/data/values_success.csv", { cache: "no-store" }).then((res) => {
          if (!res.ok) {
            throw new Error("values_success.csv load failed");
          }
          return res.text();
        }),
        fetch("assets/data/values_fail.csv", { cache: "no-store" }).then((res) => {
          if (!res.ok) {
            throw new Error("values_fail.csv load failed");
          }
          return res.text();
        }),
      ]);

      valuesState.success = parseValueCsv(successText);
      valuesState.fail = parseValueCsv(failText);

      if (!valuesState.success.length || !valuesState.fail.length) {
        throw new Error("value CSV files are empty");
      }

      const min = Math.min(valuesState.success[0].step, valuesState.fail[0].step);
      const max = Math.max(
        valuesState.success[valuesState.success.length - 1].step,
        valuesState.fail[valuesState.fail.length - 1].step
      );

      valuesState.minStep = min;
      valuesState.maxStep = max;
      valuesState.currentStep = min;

      buildValuesChart();
      bindValuesLockToggle();
      observeValuesChartResize();
      primeValuesVideos();
    } catch (error) {
      const status = document.getElementById("values-status");
      if (status) {
        status.textContent = "Value timeline could not be loaded.";
      }
    }
  }

  async function initConsistencyLossChart() {
    const svg = document.getElementById("slip-consistency-chart");
    if (!svg) {
      return;
    }

    try {
      const [pretrainedText, finetunedText] = await Promise.all([
        fetch("assets/data/consist_losses.csv", { cache: "no-store" }).then((res) => {
          if (!res.ok) {
            throw new Error("consist_losses.csv load failed");
          }
          return res.text();
        }),
        fetch("assets/data/consist_losses_ft.csv", { cache: "no-store" }).then((res) => {
          if (!res.ok) {
            throw new Error("consist_losses_ft.csv load failed");
          }
          return res.text();
        }),
      ]);

      consistencyState.pretrained = parseSingleColumnCsv(pretrainedText);
      consistencyState.finetuned = parseSingleColumnCsv(finetunedText);

      if (!consistencyState.pretrained.length || !consistencyState.finetuned.length) {
        throw new Error("consistency loss CSV files are empty");
      }

      bindConsistencyLegendControls();
      refreshConsistencyLegendUI();
      buildConsistencyLossChart();
      observeConsistencyChartResize();
    } catch (error) {
      const status = document.getElementById("slip-chart-status");
      if (status) {
        status.textContent = "Consistency loss chart could not be loaded.";
      }
    }
  }

  function parseValueCsv(text) {
    const rows = text.trim().split(/\r?\n/);
    const points = [];

    for (const row of rows) {
      const parts = row.split(",");
      if (parts.length < 2) {
        continue;
      }

      const step = Number(parts[0]);
      const value = Number(parts[1]);
      if (Number.isFinite(step) && Number.isFinite(value)) {
        points.push({ step, value });
      }
    }

    return points;
  }

  function parseSingleColumnCsv(text) {
    const rows = text.trim().split(/\r?\n/);
    const values = [];

    for (const row of rows) {
      const raw = row.trim();
      if (!raw) {
        continue;
      }
      const value = Number(raw.split(",")[0]);
      if (Number.isFinite(value)) {
        values.push(value);
      }
    }

    return values;
  }

  function primeValuesVideos() {
    const successVideo = document.getElementById("values-video-success");
    const failVideo = document.getElementById("values-video-fail");
    if (!successVideo || !failVideo) {
      return;
    }

    const syncCurrentFrame = () => {
      if (valuesState.chart) {
        setValuesStep(valuesState.currentStep, valuesState.chart);
      }
    };

    for (const video of [successVideo, failVideo]) {
      if (video.dataset.valuesPrimed !== "true") {
        video.dataset.valuesPrimed = "true";
        video.setAttribute("preload", "auto");
        video.muted = true;
        video.addEventListener("loadedmetadata", syncCurrentFrame);
        video.addEventListener("durationchange", syncCurrentFrame);
        video.addEventListener("canplay", syncCurrentFrame);
      }

      if (video.readyState === 0) {
        try {
          video.load();
        } catch (error) {
          continue;
        }
      }

      hydrateValuesVideo(video).then(syncCurrentFrame);
      warmupValuesVideo(video, syncCurrentFrame);
    }

    syncCurrentFrame();
  }

  function warmupValuesVideo(video, onReady) {
    if (!video || video.dataset.valuesWarmupTried === "true") {
      return;
    }

    video.dataset.valuesWarmupTried = "true";
    const tryWarmup = () => {
      const playPromise = video.play();
      if (playPromise && typeof playPromise.then === "function") {
        playPromise
          .then(() => {
            video.pause();
            if (typeof onReady === "function") {
              onReady();
            }
          })
          .catch(() => {});
      }
    };

    if (video.readyState >= 2) {
      tryWarmup();
      return;
    }

    video.addEventListener("canplay", tryWarmup, { once: true });
  }

  async function hydrateValuesVideo(video) {
    if (!video || video.dataset.valuesHydrateTried === "true") {
      return;
    }

    video.dataset.valuesHydrateTried = "true";
    const source = video.querySelector("source");
    const src = source ? source.getAttribute("src") : video.getAttribute("src");
    if (!src) {
      return;
    }

    try {
      const response = await fetch(src, { cache: "no-store" });
      if (!response.ok) {
        return;
      }

      const blob = await response.blob();
      const objectUrl = URL.createObjectURL(blob);
      valuesState.objectUrls.push(objectUrl);
      video.setAttribute("src", objectUrl);
      video.load();
    } catch (error) {
      return;
    }
  }

  function buildValuesChart() {
    const svg = document.getElementById("values-chart");
    if (!svg) {
      return;
    }

    const DEFAULT_WIDTH = 900;
    const DEFAULT_HEIGHT = 460;
    const bounds = svg.getBoundingClientRect();
    const width = Math.round(bounds.width) > 0 ? Math.round(bounds.width) : DEFAULT_WIDTH;
    const height = Math.round(bounds.height) > 0 ? Math.round(bounds.height) : DEFAULT_HEIGHT;
    valuesState.lastWidth = width;
    valuesState.lastHeight = height;
    const margin = { top: 18, right: 12, bottom: 42, left: 50 };
    const plotWidth = width - margin.left - margin.right;
    const plotHeight = height - margin.top - margin.bottom;
    svg.setAttribute("viewBox", "0 0 " + width + " " + height);

    const success = valuesState.success;
    const fail = valuesState.fail;

    const allValues = success.map((point) => point.value).concat(fail.map((point) => point.value));
    let yMin = Math.min.apply(null, allValues);
    let yMax = Math.max.apply(null, allValues);
    const pad = (yMax - yMin || 1) * 0.08;
    yMin -= pad;
    yMax += pad;

    const xMin = valuesState.minStep;
    const xMax = valuesState.maxStep;

    const scaleX = (x) => margin.left + ((x - xMin) / (xMax - xMin || 1)) * plotWidth;
    const scaleY = (y) => margin.top + (1 - (y - yMin) / (yMax - yMin || 1)) * plotHeight;

    svg.innerHTML = "";

    svg.appendChild(
      createSvgElement("rect", {
        x: margin.left,
        y: margin.top,
        width: plotWidth,
        height: plotHeight,
        fill: "#ffffff",
        stroke: "rgba(16, 23, 34, 0.16)",
        "stroke-width": "1",
        rx: "8",
      })
    );

    const yTicks = 5;
    for (let i = 0; i < yTicks; i += 1) {
      const t = i / (yTicks - 1);
      const y = margin.top + t * plotHeight;
      const value = yMin + (1 - t) * (yMax - yMin);

      svg.appendChild(
        createSvgElement("line", {
          x1: margin.left,
          y1: y,
          x2: margin.left + plotWidth,
          y2: y,
          stroke: "rgba(16, 23, 34, 0.12)",
          "stroke-width": "0.8",
        })
      );

      svg.appendChild(
        createSvgElement("text", {
          x: margin.left - 8,
          y: y + 4,
          fill: "#49576a",
          "font-size": "11",
          "text-anchor": "end",
          "font-family": "Sora, sans-serif",
          textContent: formatTick(value),
        })
      );
    }

    const xTickCount = 6;
    for (let i = 0; i < xTickCount; i += 1) {
      const t = i / (xTickCount - 1);
      const step = Math.round(xMin + t * (xMax - xMin));
      const x = scaleX(step);

      svg.appendChild(
        createSvgElement("line", {
          x1: x,
          y1: margin.top,
          x2: x,
          y2: margin.top + plotHeight,
          stroke: "rgba(16, 23, 34, 0.08)",
          "stroke-width": "0.8",
        })
      );

      svg.appendChild(
        createSvgElement("text", {
          x,
          y: margin.top + plotHeight + 18,
          fill: "#49576a",
          "font-size": "11",
          "text-anchor": "middle",
          "font-family": "Sora, sans-serif",
          textContent: String(step),
        })
      );
    }

    svg.appendChild(
      createSvgElement("path", {
        d: toPath(success, scaleX, scaleY),
        fill: "none",
        stroke: "#0f7f66",
        "stroke-width": "2.6",
        "stroke-linecap": "round",
        "stroke-linejoin": "round",
      })
    );

    svg.appendChild(
      createSvgElement("path", {
        d: toPath(fail, scaleX, scaleY),
        fill: "none",
        stroke: "#c95a2a",
        "stroke-width": "2.6",
        "stroke-linecap": "round",
        "stroke-linejoin": "round",
      })
    );

    svg.appendChild(
      createSvgElement("text", {
        x: margin.left + 6,
        y: margin.top + 14,
        fill: "#0f7f66",
        "font-size": "12",
        "font-family": "Sora, sans-serif",
        textContent: "Success",
      })
    );

    svg.appendChild(
      createSvgElement("text", {
        x: margin.left + 78,
        y: margin.top + 14,
        fill: "#c95a2a",
        "font-size": "12",
        "font-family": "Sora, sans-serif",
        textContent: "Failure",
      })
    );

    const cursorLine = createSvgElement("line", {
      x1: scaleX(valuesState.minStep),
      y1: margin.top,
      x2: scaleX(valuesState.minStep),
      y2: margin.top + plotHeight,
      stroke: "#0b9ab6",
      "stroke-width": "1.4",
      "stroke-dasharray": "5 4",
    });

    const successDot = createSvgElement("circle", {
      cx: scaleX(valuesState.minStep),
      cy: scaleY(success[0].value),
      r: "4",
      fill: "#ffffff",
      stroke: "#0f7f66",
      "stroke-width": "2",
    });

    const failDot = createSvgElement("circle", {
      cx: scaleX(valuesState.minStep),
      cy: scaleY(fail[0].value),
      r: "4",
      fill: "#ffffff",
      stroke: "#c95a2a",
      "stroke-width": "2",
    });

    svg.appendChild(cursorLine);
    svg.appendChild(successDot);
    svg.appendChild(failDot);

    svg.appendChild(
      createSvgElement("text", {
        x: margin.left + plotWidth / 2,
        y: height - 8,
        fill: "#3a4657",
        "font-size": "11",
        "font-family": "Sora, sans-serif",
        "text-anchor": "middle",
        textContent: "Step index",
      })
    );

    svg.appendChild(
      createSvgElement("text", {
        x: 14,
        y: margin.top + plotHeight / 2,
        fill: "#3a4657",
        "font-size": "11",
        "font-family": "Sora, sans-serif",
        "text-anchor": "middle",
        transform: "rotate(-90 14 " + (margin.top + plotHeight / 2) + ")",
        textContent: "Predicted value",
      })
    );

    const eventRect = createSvgElement("rect", {
      x: margin.left,
      y: margin.top,
      width: plotWidth,
      height: plotHeight,
      fill: "rgba(0, 0, 0, 0.001)",
      "pointer-events": "all",
      "touch-action": "none",
      cursor: "crosshair",
    });

    let draggingPointerId = null;
    const updateFromPointerEvent = (event) => {
      const step = stepFromEvent(event, svg, margin.left, plotWidth, xMin, xMax);
      setValuesStep(step, {
        cursorLine,
        successDot,
        failDot,
        scaleX,
        scaleY,
      });
    };

    eventRect.addEventListener("pointerdown", (event) => {
      draggingPointerId = event.pointerId;
      if (eventRect.setPointerCapture) {
        eventRect.setPointerCapture(event.pointerId);
      }
      updateFromPointerEvent(event);
    });

    eventRect.addEventListener("pointermove", (event) => {
      const isDragging = draggingPointerId === event.pointerId;
      if (!isDragging && valuesState.locked) {
        return;
      }
      updateFromPointerEvent(event);
    });

    const stopDragging = (event) => {
      if (draggingPointerId !== event.pointerId) {
        return;
      }
      if (eventRect.hasPointerCapture && eventRect.hasPointerCapture(event.pointerId)) {
        eventRect.releasePointerCapture(event.pointerId);
      }
      draggingPointerId = null;
    };

    eventRect.addEventListener("pointerup", stopDragging);
    eventRect.addEventListener("pointercancel", stopDragging);
    eventRect.addEventListener("click", updateFromPointerEvent);

    if (!("PointerEvent" in window)) {
      eventRect.addEventListener("mousemove", (event) => {
        if (valuesState.locked) {
          return;
        }
        updateFromPointerEvent(event);
      });

      eventRect.addEventListener("mousedown", updateFromPointerEvent);
    }

    svg.appendChild(eventRect);

    valuesState.chart = {
      cursorLine,
      successDot,
      failDot,
      scaleX,
      scaleY,
    };

    setValuesStep(valuesState.currentStep, valuesState.chart);
  }

  function bindConsistencyLegendControls() {
    const legend = document.querySelector(".slip-chart-legend");
    if (!legend || legend.dataset.bound === "true") {
      return;
    }

    legend.dataset.bound = "true";

    const buttons = Array.from(legend.querySelectorAll(".slip-legend-item[data-series]"));
    for (const button of buttons) {
      const seriesName = button.dataset.series;
      if (!seriesName) {
        continue;
      }

      button.addEventListener("mouseenter", () => {
        consistencyState.hovered = seriesName;
        refreshConsistencyLegendUI();
        buildConsistencyLossChart();
      });

      button.addEventListener("mouseleave", () => {
        if (consistencyState.hovered === seriesName) {
          consistencyState.hovered = null;
          refreshConsistencyLegendUI();
          buildConsistencyLossChart();
        }
      });

      button.addEventListener("focus", () => {
        consistencyState.hovered = seriesName;
        refreshConsistencyLegendUI();
        buildConsistencyLossChart();
      });

      button.addEventListener("blur", () => {
        if (consistencyState.hovered === seriesName) {
          consistencyState.hovered = null;
          refreshConsistencyLegendUI();
          buildConsistencyLossChart();
        }
      });

      button.addEventListener("click", () => {
        if (consistencyState.hidden.has(seriesName)) {
          consistencyState.hidden.delete(seriesName);
        } else {
          consistencyState.hidden.add(seriesName);
        }
        refreshConsistencyLegendUI();
        buildConsistencyLossChart();
      });
    }
  }

  function refreshConsistencyLegendUI() {
    const buttons = document.querySelectorAll(".slip-legend-item[data-series]");
    for (const button of buttons) {
      const seriesName = button.dataset.series;
      const hidden = consistencyState.hidden.has(seriesName);
      const hovered = consistencyState.hovered === seriesName;
      button.setAttribute("aria-pressed", hidden ? "true" : "false");
      button.classList.toggle("is-hovered", hovered);
    }
  }

  function buildConsistencyLossChart() {
    const svg = document.getElementById("slip-consistency-chart");
    if (!svg) {
      return;
    }

    const pretrained = consistencyState.pretrained;
    const finetuned = consistencyState.finetuned;
    if (!pretrained.length || !finetuned.length) {
      return;
    }

    const DEFAULT_WIDTH = 900;
    const DEFAULT_HEIGHT = 420;
    const bounds = svg.getBoundingClientRect();
    const width = Math.round(bounds.width) > 0 ? Math.round(bounds.width) : DEFAULT_WIDTH;
    const height =
      Math.round(bounds.height) > 0 ? Math.round(bounds.height) : Math.round((width / DEFAULT_WIDTH) * DEFAULT_HEIGHT);

    consistencyState.lastWidth = width;
    consistencyState.lastHeight = height;

    const margin = { top: 18, right: 14, bottom: 46, left: 64 };
    const plotWidth = Math.max(10, width - margin.left - margin.right);
    const plotHeight = Math.max(10, height - margin.top - margin.bottom);
    const seriesLength = Math.max(pretrained.length, finetuned.length);
    const xMin = 0;
    const xMax = Math.max(0, seriesLength - 1);

    const visibleValues = [];
    if (!consistencyState.hidden.has("pretrained")) {
      visibleValues.push.apply(visibleValues, pretrained);
    }
    if (!consistencyState.hidden.has("finetuned")) {
      visibleValues.push.apply(visibleValues, finetuned);
    }
    if (!visibleValues.length) {
      visibleValues.push.apply(visibleValues, pretrained);
      visibleValues.push.apply(visibleValues, finetuned);
    }

    let yMin = 0;
    let yMax = Math.max.apply(null, visibleValues);
    yMax = Math.max(0.01, yMax * 1.08);
    if (Math.abs(yMax - yMin) < 1e-9) {
      yMax = yMin + 1;
    }

    const scaleX = (x) => margin.left + ((x - xMin) / (xMax - xMin || 1)) * plotWidth;
    const scaleY = (y) => margin.top + (1 - (y - yMin) / (yMax - yMin || 1)) * plotHeight;

    svg.setAttribute("viewBox", "0 0 " + width + " " + height);
    svg.innerHTML = "";

    svg.appendChild(
      createSvgElement("rect", {
        x: margin.left,
        y: margin.top,
        width: plotWidth,
        height: plotHeight,
        fill: "#ffffff",
        stroke: "rgba(16, 23, 34, 0.16)",
        "stroke-width": "1",
        rx: "8",
      })
    );

    const yTicks = 5;
    for (let i = 0; i < yTicks; i += 1) {
      const t = i / (yTicks - 1);
      const y = margin.top + t * plotHeight;
      const value = yMin + (1 - t) * (yMax - yMin);
      svg.appendChild(
        createSvgElement("line", {
          x1: margin.left,
          y1: y,
          x2: margin.left + plotWidth,
          y2: y,
          stroke: "rgba(16, 23, 34, 0.12)",
          "stroke-width": i === yTicks - 1 ? "1.05" : "0.8",
        })
      );
      svg.appendChild(
        createSvgElement("text", {
          x: margin.left - 8,
          y: y + 4,
          fill: "#49576a",
          "font-size": width < 620 ? "11" : "12",
          "text-anchor": "end",
          "font-family": "Sora, sans-serif",
          textContent: formatTick(value),
        })
      );
    }

    const xTickCount = 6;
    for (let i = 0; i < xTickCount; i += 1) {
      const t = i / (xTickCount - 1);
      const tick = Math.round(xMin + t * (xMax - xMin));
      const x = scaleX(tick);
      svg.appendChild(
        createSvgElement("line", {
          x1: x,
          y1: margin.top,
          x2: x,
          y2: margin.top + plotHeight,
          stroke: "rgba(16, 23, 34, 0.08)",
          "stroke-width": "0.8",
        })
      );
      svg.appendChild(
        createSvgElement("text", {
          x,
          y: margin.top + plotHeight + 20,
          fill: "#49576a",
          "font-size": width < 620 ? "11" : "12",
          "text-anchor": "middle",
          "font-family": "Sora, sans-serif",
          textContent: String(tick),
        })
      );
    }

    const seriesDefs = [
      { key: "pretrained", color: "#4C72B0", values: pretrained },
      { key: "finetuned", color: "#DD8452", values: finetuned },
    ];

    for (const series of seriesDefs) {
      const isHidden = consistencyState.hidden.has(series.key);
      const isHovered = consistencyState.hovered === series.key;
      const isMuted = Boolean(consistencyState.hovered && !isHovered);
      const opacity = isHidden ? 0 : isMuted ? 0.22 : 1;
      const strokeWidth = isHovered ? 3.6 : 2.8;

      const d = series.values
        .map((value, idx) => {
          const x = scaleX(idx);
          const y = scaleY(value);
          return (idx === 0 ? "M" : "L") + x.toFixed(2) + " " + y.toFixed(2);
        })
        .join(" ");

      const line = createSvgElement("path", {
        d,
        fill: "none",
        stroke: series.color,
        "stroke-width": String(strokeWidth),
        "stroke-linecap": "round",
        "stroke-linejoin": "round",
        opacity: String(opacity),
      });
      svg.appendChild(line);
    }

    svg.appendChild(
      createSvgElement("text", {
        x: margin.left + plotWidth / 2,
        y: height - 8,
        fill: "#3a4657",
        "font-size": width < 620 ? "11" : "12",
        "font-family": "Sora, sans-serif",
        "text-anchor": "middle",
        textContent: "Timestep",
      })
    );

    svg.appendChild(
      createSvgElement("text", {
        x: 18,
        y: margin.top + plotHeight / 2,
        fill: "#3a4657",
        "font-size": width < 620 ? "11" : "12",
        "font-family": "Sora, sans-serif",
        "text-anchor": "middle",
        transform: "rotate(-90 18 " + (margin.top + plotHeight / 2) + ")",
        textContent: "Latent Dynamics Loss",
      })
    );

  }

  function observeValuesChartResize() {
    const svg = document.getElementById("values-chart");
    if (!svg || !("ResizeObserver" in window)) {
      return;
    }

    if (valuesState.resizeObserver) {
      valuesState.resizeObserver.disconnect();
    }

    valuesState.resizeObserver = new ResizeObserver(() => {
      const bounds = svg.getBoundingClientRect();
      const width = Math.round(bounds.width);
      const height = Math.round(bounds.height);

      if (width <= 0 || height <= 0) {
        return;
      }

      if (width === valuesState.lastWidth && height === valuesState.lastHeight) {
        return;
      }

      if (valuesState.resizeRaf) {
        window.cancelAnimationFrame(valuesState.resizeRaf);
      }

      valuesState.resizeRaf = window.requestAnimationFrame(() => {
        valuesState.resizeRaf = 0;
        buildValuesChart();
      });
    });

    valuesState.resizeObserver.observe(svg);
  }

  function observeConsistencyChartResize() {
    const svg = document.getElementById("slip-consistency-chart");
    if (!svg || !("ResizeObserver" in window)) {
      return;
    }

    if (consistencyState.resizeObserver) {
      consistencyState.resizeObserver.disconnect();
    }

    consistencyState.resizeObserver = new ResizeObserver(() => {
      const bounds = svg.getBoundingClientRect();
      const width = Math.round(bounds.width);
      const height = Math.round(bounds.height);

      if (width <= 0 || height <= 0) {
        return;
      }

      if (width === consistencyState.lastWidth && height === consistencyState.lastHeight) {
        return;
      }

      if (consistencyState.resizeRaf) {
        window.cancelAnimationFrame(consistencyState.resizeRaf);
      }

      consistencyState.resizeRaf = window.requestAnimationFrame(() => {
        consistencyState.resizeRaf = 0;
        buildConsistencyLossChart();
      });
    });

    consistencyState.resizeObserver.observe(svg);
  }

  function bindValuesLockToggle() {
    const lockButton = document.getElementById("values-lock");
    const lockLabel = document.getElementById("values-lock-label");
    const status = document.getElementById("values-status");
    const successVideo = document.getElementById("values-video-success");
    const failVideo = document.getElementById("values-video-fail");

    if (!lockButton || !status || !successVideo || !failVideo) {
      return;
    }

    const setLockLabel = (text) => {
      if (lockLabel) {
        lockLabel.textContent = text;
      } else {
        lockButton.textContent = text;
      }
    };

    lockButton.addEventListener("click", () => {
      valuesState.locked = !valuesState.locked;
      lockButton.setAttribute("aria-pressed", valuesState.locked ? "true" : "false");

      if (valuesState.locked) {
        setLockLabel("Unlock Frame");
        status.textContent = useTouchInteractionCopy()
          ? INTERACTION_COPY.valuesLocked.touch
          : INTERACTION_COPY.valuesLocked.desktop;
        successVideo.pause();
        failVideo.pause();
      } else {
        setLockLabel("Lock Frame");
        status.textContent = useTouchInteractionCopy()
          ? INTERACTION_COPY.valuesStatus.touch
          : INTERACTION_COPY.valuesStatus.desktop;
        successVideo.pause();
        failVideo.pause();
        if (valuesState.chart) {
          setValuesStep(valuesState.currentStep, valuesState.chart);
        }
      }
    });
  }

  function setValuesStep(step, chartRefs) {
    const successSeries = valuesState.success;
    const failSeries = valuesState.fail;
    if (!successSeries.length || !failSeries.length) {
      return;
    }

    const clamped = Math.max(valuesState.minStep, Math.min(valuesState.maxStep, Math.round(step)));
    valuesState.currentStep = clamped;

    const successPoint = pointAtStep(successSeries, clamped);
    const failPoint = pointAtStep(failSeries, clamped);

    if (chartRefs) {
      const x = chartRefs.scaleX(clamped);
      chartRefs.cursorLine.setAttribute("x1", x);
      chartRefs.cursorLine.setAttribute("x2", x);
      chartRefs.successDot.setAttribute("cx", x);
      chartRefs.successDot.setAttribute("cy", chartRefs.scaleY(successPoint.value));
      chartRefs.failDot.setAttribute("cx", x);
      chartRefs.failDot.setAttribute("cy", chartRefs.scaleY(failPoint.value));
    }

    const ratio = (clamped - valuesState.minStep) / (valuesState.maxStep - valuesState.minStep || 1);
    const successVideo = document.getElementById("values-video-success");
    const failVideo = document.getElementById("values-video-fail");
    syncVideoToRatio(successVideo, ratio);
    syncVideoToRatio(failVideo, ratio);
  }

  function stepFromEvent(event, svg, xOrigin, plotWidth, minStep, maxStep) {
    const rect = svg.getBoundingClientRect();
    const viewWidth = svg.viewBox && svg.viewBox.baseVal ? svg.viewBox.baseVal.width : 0;
    const localX = (event.clientX - rect.left) / (rect.width || 1);
    const xSvg = localX * (viewWidth || rect.width || 1);
    const normalized = Math.max(0, Math.min(1, (xSvg - xOrigin) / (plotWidth || 1)));
    return minStep + normalized * (maxStep - minStep);
  }

  function pointAtStep(series, step) {
    let nearest = series[0];
    let bestDist = Math.abs(nearest.step - step);

    for (let i = 1; i < series.length; i += 1) {
      const point = series[i];
      const dist = Math.abs(point.step - step);
      if (dist < bestDist) {
        nearest = point;
        bestDist = dist;
      }
    }

    return nearest;
  }

  function syncVideoToRatio(video, ratio) {
    if (!video) {
      return;
    }

    const boundedRatio = Math.max(0, Math.min(1, ratio));
    let scrub = valuesState.videoScrubState.get(video);
    if (!scrub) {
      scrub = { ratio: boundedRatio, raf: 0 };
      valuesState.videoScrubState.set(video, scrub);
    }

    scrub.ratio = boundedRatio;
    if (scrub.raf) {
      return;
    }

    scrub.raf = window.requestAnimationFrame(() => {
      scrub.raf = 0;
      applyVideoScrub(video, scrub.ratio);
    });
  }

  function applyVideoScrub(video, ratio) {
    if (!video) {
      return;
    }

    video.pause();

    const hasFiniteDuration = Number.isFinite(video.duration) && video.duration > 0;
    const seekableDuration =
      video.seekable && video.seekable.length > 0 ? video.seekable.end(video.seekable.length - 1) : 0;
    const effectiveDuration = hasFiniteDuration ? video.duration : seekableDuration;

    if (!Number.isFinite(effectiveDuration) || effectiveDuration <= 0) {
      if (video.dataset.valuesLoadRequested !== "true") {
        video.dataset.valuesLoadRequested = "true";
        try {
          video.load();
        } catch (error) {
          return;
        }
      }
      return;
    }

    let target = Math.max(0, Math.min(1, ratio)) * effectiveDuration;
    if (video.seekable && video.seekable.length > 0) {
      const rangeStart = video.seekable.start(0);
      const rangeEnd = video.seekable.end(video.seekable.length - 1);
      target = Math.max(rangeStart, Math.min(rangeEnd - 0.001, target));
    }

    if (Math.abs(video.currentTime - target) <= 1 / 24) {
      return;
    }

    try {
      if (typeof video.fastSeek === "function") {
        video.fastSeek(target);
      } else {
        video.currentTime = target;
      }
    } catch (error) {
      return;
    }
  }

  function pickXAxisTicks(values) {
    if (!values.length) {
      return [0];
    }

    if (values.length <= 4) {
      return values;
    }

    const picks = [values[0]];
    const mid = values[Math.floor((values.length - 1) / 2)];
    picks.push(mid);
    const quarter = values[Math.floor((values.length - 1) / 4)];
    const threeQuarter = values[Math.floor(((values.length - 1) * 3) / 4)];
    picks.push(quarter, threeQuarter);
    picks.push(values[values.length - 1]);

    return Array.from(new Set(picks)).sort((a, b) => a - b);
  }

  function toPath(points, scaleX, scaleY) {
    return points
      .map((point, idx) => {
        const x = scaleX(point.step);
        const y = scaleY(point.value);
        return (idx === 0 ? "M" : "L") + x.toFixed(2) + " " + y.toFixed(2);
      })
      .join(" ");
  }

  function colorForMethod(methodName) {
    if (METHOD_COLOR_MAP[methodName]) {
      return METHOD_COLOR_MAP[methodName];
    }

    let hash = 0;
    for (let i = 0; i < methodName.length; i += 1) {
      hash = (hash << 5) - hash + methodName.charCodeAt(i);
      hash |= 0;
    }

    const hue = Math.abs(hash) % 360;
    return "hsl(" + hue + " 58% 42%)";
  }

  function formatTick(value) {
    if (Math.abs(value) >= 10) {
      return value.toFixed(1);
    }

    if (Math.abs(value) >= 1) {
      return value.toFixed(2);
    }

    return value.toFixed(2);
  }

  function createSvgElement(name, attrs) {
    const node = document.createElementNS("http://www.w3.org/2000/svg", name);
    for (const [key, value] of Object.entries(attrs)) {
      if (key === "textContent") {
        node.textContent = value;
      } else {
        node.setAttribute(key, String(value));
      }
    }
    return node;
  }

  function safePlay(video) {
    if (!video) {
      return;
    }

    video.muted = true;
    const playPromise = video.play();
    if (playPromise && typeof playPromise.catch === "function") {
      playPromise.catch(() => {});
    }
  }

  window.addEventListener("beforeunload", () => {
    for (const url of valuesState.objectUrls) {
      URL.revokeObjectURL(url);
    }
    valuesState.objectUrls = [];
  });
})();
